apiVersion: v1
metadata:
  name: cluster1
baseDomain: sg-sa.de
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      zones:
      - ap-southeast-1b
      rootVolume:
        iops: 4000
        size: 100
        type: io1
      type: m5.xlarge
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 1
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.xlarge
      zones:
      - ap-southeast-1b
networking:
  clusterNetwork:
  - cidr: 10.127.0.0/16
    hostPrefix: 23
  machineCIDR: 10.1.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.31.0.0/16
platform:
  aws:
    region: ap-southeast-1
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1h+lATASMLn7FGaZEH74W87cj7bk7tknxwPUpau8lIZXUY7/i1ftylK5rBeAdx4eC/FpbEj1uqO6ycdgTDqKs7fT/9tSI1PDKfOa3Fi1MuLn+3Yon5QSi9WheVEZ61qSp+ldYMR/Xlr1bDQ9T4yy1hTJ4/cXoa9+QOuFZmiYRL9TakGcxd97Q3gedGNTHynwukNijq1cFXG9GYy5Z1+y6LRE0k3wNFiIAXsDbIrbRLrvGcVDkV5X5rIsdxeRK/i0463D9BtHaa9DCyGYZmnWjlqMxvhTjBuFkTa3ZpXpK8V/EbrWglCYlK8/80fBFaPjkwxIHNvPskUQOOU+cxLg1 kashukla@Redhats-MacBook-Pro.local
